### ISSUE TITLE
Running hyprfreeze without args should default to -a

### ISSUE THREAD

**Issue by IceDBorn** [Zerodya/hyprfreeze#4]

**Comment by Zerodya** [comment]
I don't plan on doing this since what the script does right now is the intended behavior. 

The old script was defaulting to pausing the active window just because there were no other options, but now there are 4 multiple modes in v0.1.0, and the user should choose the corresponding flag consciously.

Running just `hyprfreeze` in terminal would pause the hyprfreeze process itself, which would lead to the terminal window no longer responding and possibly freezing the entire system (of course I put a check in place so that these kind of things won't happen, but still).

Instead, what the script does right now, is inform the user that there are multiple options available through an help screen if they just type `hyprfreeze` in a terminal to see how it works. Similar tools like [Hyprshot](https://github.com/Gustash/Hyprshot) also work like this.

So I think this is the best behavior unless there is a good reason against it.

**Comment by IceDBorn** [comment]
You're right, I did not think of that. I'm closing the issue.
